-- MySQL Script generated by MySQL Workbench
-- 03/18/20 20:12:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profissoes` (
  `id` INT NOT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `cpf` VARCHAR(11) NULL COMMENT '',
  `data_nascimento` DATE NULL COMMENT '',
  `profissoes_id` INT NOT NULL COMMENT '',
  `cor` VARCHAR(45) NULL COMMENT '',
  `historico` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pacientes_profissoes_idx` (`profissoes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pacientes_profissoes`
    FOREIGN KEY (`profissoes_id`)
    REFERENCES `mydb`.`profissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamento` (
  `id` INT NOT NULL COMMENT '',
  `pacientes_id` INT NOT NULL COMMENT '',
  `hora_inicio` TIME NULL COMMENT '',
  `hora_fim` TIME NULL COMMENT '',
  `data_inicio` DATE NULL COMMENT '',
  `data_fim` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_agendamento_pacientes1_idx` (`pacientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_agendamento_pacientes1`
    FOREIGN KEY (`pacientes_id`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultas` (
  `id` INT NOT NULL COMMENT '',
  `agendamento_id` INT NOT NULL COMMENT '',
  `presenca` VARCHAR(1) NULL COMMENT '',
  `obs` TEXT NULL COMMENT '',
  `receituario` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_consultas_agendamento1_idx` (`agendamento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_consultas_agendamento1`
    FOREIGN KEY (`agendamento_id`)
    REFERENCES `mydb`.`agendamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
